server:
  port: 8081

spring:
  application:
    name: pure_client

  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            client-id: ${OAUTH2_PURE_CLIENT_CLIENT_ID}
            client-secret: ${OAUTH2_PURE_CLIENT_CLIENT_SECRET}
            scope: openid
            authorization-grant-type: client_credentials

        provider:
          keycloak-client:
            token-uri: ${OAUTH2_PURE_CLIENT_PROVIDER_TOKEN_URI}

resource-service:
  uri: http://localhost:8082
