build:
  id: 101
  version: 1.9.5
  name: Production Build

app:
  welcomeMessage: "Welcome to the Prod Environment!"
  maxLoginAttempts: 6
  featureToggles:
    newDashboard: true
    betaFeatures: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
